### ISSUE TITLE
Building cycle stuck

### ISSUE THREAD

**Issue by andrepacak** [pluto-build/build-java#4]
I tried to compile the monto-editor/services-base-java repository with the new fix. But now it is stuck.

This is a snippet of the output. The time it takes to execute increases. At the last step I observed the compilation took 8289ms to succeed.

  Compile Java files AST.java
    Compile Java files IRegion.java ... succeeded - 648ms
    Compile Java files ASTVisitor.java
      Compile Java files NonTerminal.java
        Detected a dependency cycle with root /Users/andiderp/repos/pluto-ecosystem/build-monto/targetsb/compile.java.604626449.dep
        Build cycle with: Compile Java files AST.java, ASTVisitor.java, NonTerminal.java
          Compile Java files IRegion.java ... succeeded - 674ms
          Compile Java files Terminal.java
            Compile Java files AST.java
              Compile Java files ASTVisitor.java
                Compile Java files NonTerminal.java
                  Detected a dependency cycle with root /Users/andiderp/repos/pluto-ecosystem/build-monto/targetsb/compile.java.604626449.dep
                  Build cycle with: Compile Java files AST.java, ASTVisitor.java, NonTerminal.java
                    Compile Java files IRegion.java ... succeeded - 654ms
                    Compile Java files Terminal.java
                      Compile Java files AST.java
                        Compile Java files ASTVisitor.java
                          Compile Java files NonTerminal.java
                            Detected a dependency cycle with root /Users/andiderp/repos/pluto-ecosystem/build-monto/targetsb/compile.java.604626449.dep
                            Build cycle with: Compile Java files AST.java, ASTVisitor.java, NonTerminal.java
                              Compile Java files IRegion.java ... succeeded - 642ms
                              Compile Java files Terminal.java
                                Compile Java files AST.java
                                  Compile Java files ASTVisitor.java
                                    Compile Java files NonTerminal.java
                                      Detected a dependency cycle with root /Users/andiderp/repos/pluto-ecosystem/build-monto/targetsb/compile.java.604626449.dep
                                      Build cycle with: Compile Java files AST.java, ASTVisitor.java, NonTerminal.java
                                        Compile Java files IRegion.java ... succeeded - 672ms
                                        Compile Java files Terminal.java
                                          Compile Java files AST.java
                                            Compile Java files ASTVisitor.java
                                              Compile Java files NonTerminal.java
                                                Detected a dependency cycle with root /Users/andiderp/repos/pluto-ecosystem/build-monto/targetsb/compile.java.604626449.dep
                                                Build cycle with: Compile Java files AST.java, ASTVisitor.java, NonTerminal.java
                                                  Compile Java files IRegion.java ... succeeded - 794ms
                                                  Compile Java files Terminal.java
                                                    Compile Java files AST.java
                                                      Compile Java files ASTVisitor.java
                                                        Compile Java files NonTerminal.java
                                                          Detected a dependency cycle with root /Users/andiderp/repos/pluto-ecosystem/build-monto/targetsb/compile.java.604626449.dep
                                                          Build cycle with: Compile Java files AST.java, ASTVisitor.java, NonTerminal.java

I will try to create an example and commit it to https://github.com/andiderp/build-java-bug-example

**Comment by seba--** [comment]
What is stuck? Does it loop? How do you call the builder?

**Comment by andrepacak** [comment]
It does loop. It detects the cycle compiles it. But after the compilation it finds the same cycle again and compiles it again.

The builder gets called like this:

``` java
        for (Path p : javaSrcPathList) {
            JavaInput javaInput = new JavaInput(
                    p.toFile(),
                    input.target,
                    sourcePath,
                    mavenOutput.val(),
                    null,
                    requiredUnits,
                    JavacCompiler.instance);
            requireBuild(JavaBuilder.request(javaInput));
        }
```

Where requiredUnits contains a BuildRequest of the builder for fetching maven dependencies and mavenOutput.val() contains a list of files that point to the jars that the project needs.

**Comment by seba--** [comment]
It's better to call the Java compiler once, giving it all source files: https://github.com/andiderp/build-java-bug-example/pull/2.

At least, this is a workaround for your use case. We are still investigating what the best way is to build many interconnected source files with pluto.
