### ISSUE TITLE
JavaJar -C arguments

### ISSUE THREAD

**Issue by andrepacak** [pluto-build/build-java#5]
They way you aggregate the the arguments for -C does not work it only finds the first file you give it.

You could fix that by generating a String that looks like this  "-C test X.class -C test Y.class"
for a directory test that contains the two files X.class and Y.class

Alternatively you could add an attribute of List<File>, for all the classfiles you want to include into the jar, to JavaJar.Input.

**Comment by seba--** [comment]
Fixed by adding "-C <dir>" before each class file path: https://github.com/pluto-build/build-java/commit/34e61a25b1aba44d88da77b0f058d99caeef2a87
