### ISSUE TITLE
Java incremental rebuild error due to type shadowing

### ISSUE THREAD

**Issue by llbit** [pluto-build/build-java#7]
Java has type shadowing where local types can shadow on-demand imports and default imports. I created a pull request with a test that illustrates this problem: #6 

Here is a quick summary:

```
class Test { void m(String s) {} } // String here binds to a local class if a new String class is added.
```

**Comment by seba--** [comment]
Forgot to close this issue, was fixed in 097d90d98fa385fe7b744a7a48017697811dbc0b
